spring:
  cloud.stream:
    function:
      definition: consumeAudioTags
      bindings:
        consumeAudioTags-in-0: audio-tag
    bindings:
      audio-tag:
        destination: ${KAFKA_AUDIO_TAG_TOPIC}
    default-binder: kafka
    kafka:
      binder:
        brokers: ${KAFKA_SERVER}