server:
  port: ${APP_PORT}
spring:
  cloud.stream:
    function:
      definition: consumeAudioTags;consumeSpotifyTracks;consumeTracksLikedMessage;consumePlaylistCreatedMessage
      bindings:
        consumeAudioTags-in-0: audio-tag
        consumeSpotifyTracks-in-0: spotify-track
        consumeTracksLikedMessage-in-0: liked-tracks
        consumePlaylistCreatedMessage-in-0: playlist-created
    bindings:
      audio-tag:
        destination: ${KAFKA_AUDIO_TAG_TOPIC}
      spotify-track:
        destination: ${KAFKA_SPOTIFY_TRACK_TOPIC}
      liked-tracks:
        destination: ${KAFKA_TRACK_LIKED_TOPIC}
      playlist-created:
        destination: ${KAFKA_PLAYLIST_CREATED_TOPIC}
    default-binder: kafka
    kafka:
      binder:
        brokers: ${KAFKA_SERVER}
  datasource:
    username: ${DATASOURCE_USERNAME:mozeshajdu}
    password: ${DATASOURCE_PASSWORD:mozeshajdu}
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/audiotag}
  jpa:
    hibernate.ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${SHOW_SQL:false}
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect